// Generated by scripts/build.mjs — edit src/*.js and rebuild.
// dsh-bubble-fold — display-only folding for overlong DSH message bubbles.
// Nothing here writes to the session log, the model, or the agent.
(function () {
  // Local module registry for this bundle's own sources. The host knows nothing
  // about these specifiers, so the entry must resolve them HERE and hand only
  // real platform modules (react) to the resolver the host passes into factory().
  const MODULES = {}

  // ---- ./src/fold.js
  const fold = (() => {
    // Pure fold logic — no DOM access, so it can be unit tested in plain Node.
    //
    // Anchor contract (verified against @deepseek-ai/dsh-client-ui-chat 0.2.0-rc.2):
    //   [data-chat-flow-kind="user"]           → user input row
    //     > div (userRow)
    //       > div (userStack)
    //         > div (bubble)                   ← text body we clamp
    //   [data-chat-flow-kind="assistant-step"] → assistant reply row
    //     div (AssistantMarkdown root)[data-streaming?]
    //       > div (body)                       ← markdown we clamp
    //
    // Only contract-level data-* attributes and structural descent are used; hashed
    // CSS-module class names never appear here, so a host restyle cannot break this.

    const PLUGIN_ID = 'dsh-bubble-fold'
    const ROOT_ATTRIBUTE = 'data-dsh-bubble-fold'
    const STYLE_ID = 'dsh-bubble-fold-styles'
    const STORAGE_KEY = 'dsh.bubble-fold.settings'

    const SIDE_USER = 'user'
    const SIDE_ASSISTANT = 'assistant'

    /** Where the manually adjusted composer height is remembered. */
    const COMPOSER_STORAGE_KEY = 'dsh.bubble-fold.composer-height'

    /** The host's own cap, so "reset" means the stock height. */
    const COMPOSER_DEFAULT = 336

    /** Keyboard step size for the composer height. */
    const HEIGHT_STEP = 40

    /** Collapse policy for content that is over the line budget. */
    const MODE_OVERFLOW = 'overflow'
    /** Collapse policy for every message, regardless of length. */
    const MODE_ALWAYS = 'always'

    const LIMITS = Object.freeze({
      minLines: 2,
      maxLines: 120,
      minExtraPx: 0,
      maxExtraPx: 120,
      maxDefaultCollapsedLines: 60
    })

    const DEFAULT_SETTINGS = Object.freeze({
      enabled: true,
      userEnabled: true,
      assistantEnabled: true,
      /** Always applied, even when collapsedByDefault is on. */
      userLines: 6,
      assistantLines: 10,
      /** Extra px kept below the last visible line (room for the fade + button). */
      extraPx: 34,
      /** Collapse every message, not only overlong ones. */
      collapseAll: false,
      /** Line budget used when collapseAll is on. */
      collapsedLines: 3,
      /** Never fold the newest turn's message bodies: that is what you are reading. */
      keepLatestOpen: true,
      /** Start every work-step block folded, newest turn included. */
      foldAllSteps: true,
      /** Float a small bubble 展开/收起 control below each native work-step row. */
      workStepButtons: true,
      /** Show a drag handle for manually adjusting the composer height. */
      composerResize: true
    })

    const clampInt = (value, min, max, fallback) => {
      const number = typeof value === 'number' ? value : Number.parseFloat(value)
      if (!Number.isFinite(number)) return fallback
      return Math.min(max, Math.max(min, Math.round(number)))
    }

    const clampBool = (value, fallback) => (typeof value === 'boolean' ? value : fallback)

    /** Coerce any stored/partial input into a complete, in-range settings object. */
    function normalizeSettings(input) {
      const raw = input !== null && typeof input === 'object' ? input : {}
      return {
        enabled: clampBool(raw.enabled, DEFAULT_SETTINGS.enabled),
        userEnabled: clampBool(raw.userEnabled, DEFAULT_SETTINGS.userEnabled),
        assistantEnabled: clampBool(raw.assistantEnabled, DEFAULT_SETTINGS.assistantEnabled),
        userLines: clampInt(raw.userLines, LIMITS.minLines, LIMITS.maxLines, DEFAULT_SETTINGS.userLines),
        assistantLines: clampInt(raw.assistantLines, LIMITS.minLines, LIMITS.maxLines, DEFAULT_SETTINGS.assistantLines),
        extraPx: clampInt(raw.extraPx, LIMITS.minExtraPx, LIMITS.maxExtraPx, DEFAULT_SETTINGS.extraPx),
        collapseAll: clampBool(raw.collapseAll, DEFAULT_SETTINGS.collapseAll),
        collapsedLines: clampInt(raw.collapsedLines, LIMITS.minLines, LIMITS.maxDefaultCollapsedLines, DEFAULT_SETTINGS.collapsedLines),
        keepLatestOpen: clampBool(raw.keepLatestOpen, DEFAULT_SETTINGS.keepLatestOpen),
        foldAllSteps: clampBool(raw.foldAllSteps, DEFAULT_SETTINGS.foldAllSteps),
        workStepButtons: clampBool(raw.workStepButtons, DEFAULT_SETTINGS.workStepButtons),
        composerResize: clampBool(raw.composerResize, DEFAULT_SETTINGS.composerResize)
      }
    }

    function settingsForSide(settings, side) {
      if (side === SIDE_USER) {
        return { enabled: settings.userEnabled, lines: settings.userLines }
      }
      return { enabled: settings.assistantEnabled, lines: settings.assistantLines }
    }

    /**
     * Max height for the clamp box.
     * @param lines - visible line budget.
     * @param lineHeight - resolved line height in CSS px.
     * @param extraPx - px kept below the last line for the fade and the button.
     */
    function clampHeightFor(lines, lineHeight, extraPx) {
      const height = (Number(lines) || 0) * (Number(lineHeight) || 0)
      if (!(height > 0)) return 0
      return Math.round(height + Math.max(0, Number(extraPx) || 0))
    }

    /**
     * Height of the band reserved below the last visible line, where the fade and
     * the toggle live. Kept separate from the line budget so the mask can never
     * cover a line the reader is supposed to see.
     */
    function allowanceFor(extraPx) {
      return Math.round(Math.max(0, Number(extraPx) || 0))
    }

    /**
     * Decide whether one message body should be clamped.
     * @param input.contentPx - full content height of the body.
     * @param input.lineHeight - resolved line height.
     * @param input.extraPx - px kept below the last visible line.
     */
    function shouldClamp(input) {
      const { contentPx, lineHeight, extraPx, lines, collapseAll } = input
      if (!input.sideEnabled) return false
      if (input.streaming) return false
      if (input.alreadyWrapped) return false
      if (!(contentPx > 0) || !(lineHeight > 0)) return false
      if (collapseAll) return contentPx > clampHeightFor(lines, lineHeight, extraPx)
      // Overflow mode and collapse-all share the same geometry test; the difference
      // is the line budget (per-side vs collapsedLines), which the caller supplies.
      return contentPx > clampHeightFor(lines, lineHeight, extraPx)
    }

    /** A short human label for how much is hidden, e.g. "还有 12 行". */
    function hiddenLineLabel(contentPx, visiblePx, lineHeight) {
      if (!(lineHeight > 0)) return ''
      const hidden = Math.max(0, Math.round((contentPx - visiblePx) / lineHeight))
      if (hidden <= 0) return ''
      return `还有 ${hidden} 行`
    }

    return { PLUGIN_ID, ROOT_ATTRIBUTE, STYLE_ID, STORAGE_KEY, SIDE_USER, SIDE_ASSISTANT, COMPOSER_STORAGE_KEY, COMPOSER_DEFAULT, HEIGHT_STEP, MODE_OVERFLOW, MODE_ALWAYS, LIMITS, DEFAULT_SETTINGS, normalizeSettings, settingsForSide, clampHeightFor, allowanceFor, shouldClamp, hiddenLineLabel }
  })()

  // ---- ./src/browser.js
  const browser = (() => {
    // Browser half — display-only folding of overlong user inputs and assistant replies.
    //
    // Design rules (kept deliberately strict so a host upgrade degrades softly):
    //   1. Anchors are contract data-* attributes + structural descent only.
    //   2. Movement lives in `max-height`/`padding-bottom`, never in the markup React owns.
    //   3. Nothing is written to the session log, the model, or the agent.
    //   4. Every clamp is reversible: disable the plugin and the DOM returns to stock.

    const FLOW_ITEM = '[data-chat-flow-kind]'
    const KIND_USER = 'user'
    const KIND_STEERING = 'steering'
    const KIND_ASSISTANT = 'assistant-step'
    /** The Turn's own summary row ("已完成，用时 …"); its members are the step rows. */
    const KIND_TURN_PROCESS = 'turn-process'
    /** Marks a step row the plugin folded itself, for a block the host will not. */
    const FOLD_MARK = 'data-lf-step-folded'

    /**
     * Per-frame ceiling for the clamp pass. A long conversation holds over a
     * thousand flow items; measuring them all in one frame costs a forced layout per
     * item and stalls the interface outright, so the pass yields and reschedules.
     */
    const SCAN_BUDGET_MS = 4

    /** Where the manually adjusted composer height is remembered. */
    const COMPOSER_STORAGE_KEY = 'dsh.bubble-fold.composer-height'

    /** The host's own cap, so "reset" means the stock height. */
    const COMPOSER_DEFAULT = 336

    // Ancestor markers that mean "this is not a message body" — tool output, a folded
    // process envelope, context injection, a system prompt card, or an error row.
    const SKIP_ANCESTORS = [
      '[data-turn-process-hidden]',
      '[data-turn-process-answer]',
      '[data-turn-process-inline]',
      '[data-turn-process]',
      '[data-step-process]',
      '[data-step-process-content]',
      '[data-context-fields]',
      '[data-context-text]',
      '[data-context-injection-body]',
      '[data-system-prompt-body]',
      '[data-variant]',
      '[data-error]',
      '[data-compaction-icon]',
      '[data-message-attachments]'
    ].join(',')

    // A numeric/boolean control is meaningless while its gate is off.
    const TIE = Object.freeze({
      userLines: 'userEnabled',
      assistantLines: 'assistantEnabled',
      collapsedLines: 'collapseAll'
    })
    const TIE_LABEL = Object.freeze({
      userEnabled: '折叠我的输入',
      assistantEnabled: '折叠助手回复',
      collapseAll: '全部消息都折叠'
    })

    const CSS = `
    /* The clamp wrapper inherits the bubble's own alignment so wrapping never moves it. */
    :root[data-dsh-bubble-fold] [data-lf-body] {
      position: relative !important;
      display: flex !important;
      flex-direction: column !important;
      max-width: 100% !important;
    }
    :root[data-dsh-bubble-fold] [data-lf-body="user"] {
      align-items: flex-end !important;
    }
    :root[data-dsh-bubble-fold] [data-lf-body="assistant"] {
      display: flex !important;
      flex-direction: column !important;
      align-items: flex-start !important;
      width: 100% !important;
    }
    :root[data-dsh-bubble-fold] [data-lf-clamped="1"] {
      display: block !important;
      overflow: hidden !important;
      position: relative !important;
      /* The visible box is the line budget plus a reserved band: the fade lives in
         that band, so it never washes over a line the reader is meant to see.
         Fallbacks keep an orphaned attribute harmless (0 budget, 0 band). */
      max-height: calc(var(--lf-clamp-height, 0px) + var(--lf-allowance, 0px)) !important;
      padding-bottom: var(--lf-allowance, 0px) !important;
      margin-bottom: calc(-1 * var(--lf-allowance, 0px)) !important;
      transition: max-height .18s ease !important;
    }
    :root[data-dsh-bubble-fold] [data-lf-clamped="1"]:not([data-lf-open="1"]):after {
      content: "" !important;
      position: absolute !important;
      left: 0 !important;
      right: 0 !important;
      bottom: 0 !important;
      height: var(--lf-allowance) !important;
      pointer-events: none !important;
      background: linear-gradient(to bottom, transparent, var(--lf-fade-color, var(--dsw-alias-bg-base, #ffffff)) 85%) !important;
    }
    :root[data-dsh-bubble-fold] [data-lf-clamped="1"][data-lf-open="1"] {
      max-height: none !important;
      padding-bottom: 0 !important;
      margin-bottom: 0 !important;
    }
    /* The message control is a bubble-styled capsule: rounded, softly elevated,
       with a chevron that flips between the collapsed and open states. */
    :root[data-dsh-bubble-fold] [data-lf-toggle] {
      display: inline-flex !important;
      align-items: center !important;
      gap: 4px !important;
      margin: 2px 0 0 !important;
      padding: 2px 10px 2px 8px !important;
      border: 1px solid var(--dsw-alias-border-l2, rgba(15, 23, 42, .12)) !important;
      border-radius: 999px !important;
      background: var(--dsw-alias-bg-base, #fff) !important;
      color: var(--dsw-alias-label-secondary, #68707d) !important;
      font-size: 12px !important;
      line-height: 18px !important;
      font-weight: 450 !important;
      cursor: pointer !important;
      user-select: none !important;
      white-space: nowrap !important;
      position: relative !important;
      z-index: 2 !important;
      box-shadow: 0 1px 5px rgba(15, 23, 42, .1) !important;
    }
    :root[data-dsh-bubble-fold] [data-lf-toggle] svg {
      width: 13px !important;
      height: 13px !important;
      flex: none !important;
      transition: transform .15s ease !important;
    }
    :root[data-dsh-bubble-fold] [data-lf-toggle][aria-expanded="true"] svg {
      transform: rotate(180deg) !important;
    }
    :root[data-dsh-bubble-fold] [data-lf-toggle]:hover {
      color: var(--dsw-alias-label-primary, #1f2328) !important;
      background: var(--dsw-alias-interactive-bg-hover, rgba(15, 23, 42, .05)) !important;
    }
    /* One control row sits under each folded message it acts on. */
    :root[data-dsh-bubble-fold] [data-lf-tail] {
      display: flex !important;
      align-items: center !important;
      flex-wrap: wrap !important;
      gap: 6px !important;
      margin-top: 4px !important;
    }
    /* The row must be allowed to exceed the bubble: the capsule does not fit inside
       a 70%-wide bubble, and squeezing it there overlaps the bubble's own edge. */
    :root[data-dsh-bubble-fold] [data-lf-body] + [data-lf-tail] {
      width: 100% !important;
      max-width: none !important;
    }
    :root[data-dsh-bubble-fold] [data-lf-tail="user"] {
      justify-content: flex-end !important;
    }
    :root[data-dsh-bubble-fold] [data-lf-tail="assistant"] {
      justify-content: flex-start !important;
    }
    /* display would beat the hidden attribute, so restate it */
    :root[data-dsh-bubble-fold] [data-lf-tail][hidden] {
      display: none !important;
    }
    /* The work-step fold: ONE seam per process block, sitting between the run of
       step rows and the message bubble that follows them. It never owns the state —
       clicking it clicks every host control the block covers — so the chevron
       mirrors the host's own data-open. */
    :root[data-dsh-bubble-fold] [data-lf-step-toggle] {
      display: flex !important;
      align-items: center !important;
      gap: 8px !important;
      width: 100% !important;
      box-sizing: border-box !important;
      margin: 2px 0 !important;
      padding: 0 !important;
      border: none !important;
      background: none !important;
      color: var(--dsw-alias-label-secondary, #68707d) !important;
      cursor: pointer !important;
      user-select: none !important;
      appearance: none !important;
      -webkit-appearance: none !important;
    }
    /* The hairlines turn the control into the seam that separates steps from reply. */
    :root[data-dsh-bubble-fold] [data-lf-step-toggle]::before,
    :root[data-dsh-bubble-fold] [data-lf-step-toggle]::after {
      content: "" !important;
      flex: 1 1 auto !important;
      height: 1px !important;
      background: var(--dsw-alias-border-l1, rgba(15, 23, 42, .1)) !important;
      transition: background-color .12s ease !important;
    }
    :root[data-dsh-bubble-fold] [data-lf-step-toggle] [data-lf-bubble] {
      flex: none !important;
      width: 26px !important;
      height: 26px !important;
      display: inline-flex !important;
      align-items: center !important;
      justify-content: center !important;
      border: 1px solid var(--dsw-alias-border-l2, rgba(15, 23, 42, .12)) !important;
      border-radius: 50% !important;
      background: var(--dsw-alias-bg-base, #fff) !important;
      color: var(--dsw-alias-label-secondary, #68707d) !important;
      box-shadow: 0 2px 8px rgba(15, 23, 42, .14) !important;
      transition: color .12s ease, background-color .12s ease, box-shadow .12s ease, transform .12s ease !important;
    }
    :root[data-dsh-bubble-fold] [data-lf-step-toggle] svg {
      width: 14px !important;
      height: 14px !important;
      flex: none !important;
      transition: transform .15s ease !important;
    }
    :root[data-dsh-bubble-fold] [data-lf-step-toggle][data-lf-step-open="1"] svg {
      transform: rotate(180deg) !important;
    }
    :root[data-dsh-bubble-fold] [data-lf-step-toggle]:hover [data-lf-bubble] {
      color: var(--dsw-alias-label-primary, #1f2328) !important;
      background: var(--dsw-alias-interactive-bg-hover, rgba(15, 23, 42, .05)) !important;
      transform: scale(1.08) !important;
    }
    :root[data-dsh-bubble-fold] [data-lf-step-toggle]:hover::before,
    :root[data-dsh-bubble-fold] [data-lf-step-toggle]:hover::after {
      background: var(--dsw-alias-border-l2, rgba(15, 23, 42, .22)) !important;
    }
    /* display would beat the hidden attribute, so restate it */
    :root[data-dsh-bubble-fold] [data-lf-step-toggle][hidden] {
      display: none !important;
    }
    /* Rows the plugin folded itself, for a block the host refuses to fold. */
    :root[data-dsh-bubble-fold] [data-lf-step-folded] {
      display: none !important;
    }
    :root[data-dsh-bubble-fold] [data-lf-toggle]:disabled {
      opacity: .35 !important;
      cursor: default !important;
    }
    /* Drag handle for the composer height. Purely additive: no transition on the
       drag itself, so the resize cannot flicker. */
    :root[data-dsh-bubble-fold] [data-lf-composer-handle] {
      /* The order property pins the handle to the top of the card's flex column
         regardless of where a host re-render would move it in the child list. */
      order: -1 !important;
      height: 12px !important;
      pointer-events: auto !important;
      margin: 0 8px 2px !important;
      cursor: ns-resize !important;
      position: relative !important;
      flex: none !important;
      user-select: none !important;
      touch-action: none !important;
    }
    :root[data-dsh-bubble-fold] [data-lf-composer-handle]:after {
      content: "" !important;
      position: absolute !important;
      left: 50% !important;
      top: 4px !important;
      transform: translateX(-50%) !important;
      width: 64px !important;
      height: 4px !important;
      border-radius: 2px !important;
      background: var(--dsw-alias-border-l2, rgba(15, 23, 42, .3)) !important;
      transition: background-color .12s ease !important;
    }
    :root[data-dsh-bubble-fold] [data-lf-composer-handle]:hover {
      background: var(--dsw-alias-interactive-bg-hover, rgba(15, 23, 42, .05)) !important;
    }
    :root[data-dsh-bubble-fold] [data-lf-composer-handle]:hover:after,
    :root[data-dsh-bubble-fold] [data-lf-composer-handle][data-dragging]:after {
      background: var(--dsw-alias-state-business-primary, #4f6ef7) !important;
    }
    /* A settings dialog is user-invoked and dismissible — never a standing overlay
       hovering above the composer. */
    :root[data-dsh-bubble-fold] [data-lf-scrim] {
      position: fixed !important;
      inset: 0 !important;
      z-index: 59 !important;
      background: rgba(15, 23, 42, .28) !important;
    }
    :root[data-dsh-bubble-fold] [data-lf-panel] {
      position: fixed !important;
      top: 50% !important;
      left: 50% !important;
      transform: translate(-50%, -50%) !important;
      z-index: 60 !important;
      box-sizing: border-box !important;
      width: min(320px, calc(100vw - 32px)) !important;
      padding: 12px 14px !important;
      border-radius: var(--dsw-radius-panel, 14px) !important;
      border: 1px solid var(--dsw-alias-border-l2, rgba(15, 23, 42, .12)) !important;
      background: var(--dsw-alias-bg-base, #fff) !important;
      box-shadow: var(--dsw-elevation-soft, 0 8px 28px rgba(15, 23, 42, .18)) !important;
      color: var(--dsw-alias-label-primary, #1f2328) !important;
      font-size: 13px !important;
      text-align: left !important;
    }
    :root[data-dsh-bubble-fold] [data-lf-panel] h4 {
      margin: 0 0 8px !important;
      font-size: 13px !important;
      font-weight: 600 !important;
    }
    :root[data-dsh-bubble-fold] [data-lf-panel] label {
      display: flex !important;
      align-items: center !important;
      justify-content: space-between !important;
      gap: 10px !important;
      padding: 3px 0 !important;
    }
    :root[data-dsh-bubble-fold] [data-lf-panel] input[type="number"] {
      width: 64px !important;
      box-sizing: border-box !important;
      padding: 2px 6px !important;
      border-radius: 6px !important;
      border: 1px solid var(--dsw-alias-border-l2, rgba(15, 23, 42, .12)) !important;
      background: var(--dsw-alias-bg-base, #fff) !important;
      color: inherit !important;
      font: inherit !important;
    }
    :root[data-dsh-bubble-fold] [data-lf-panel] footer {
      display: flex !important;
      justify-content: space-between !important;
      align-items: center !important;
      gap: 8px !important;
      margin-top: 10px !important;
      padding-top: 8px !important;
      border-top: 1px solid var(--dsw-alias-border-l1, rgba(15, 23, 42, .08)) !important;
    }
    :root[data-dsh-bubble-fold] [data-lf-panel] button {
      appearance: none !important;
      border: 1px solid var(--dsw-alias-border-l2, rgba(15, 23, 42, .12)) !important;
      background: transparent !important;
      color: inherit !important;
      font: inherit !important;
      padding: 2px 10px !important;
      border-radius: 999px !important;
      cursor: pointer !important;
    }
    :root[data-dsh-bubble-fold] [data-lf-panel] button:hover {
      background: var(--dsw-alias-interactive-bg-hover, rgba(15, 23, 42, .05)) !important;
    }
    :root[data-dsh-bubble-fold] [data-lf-panel] [data-lf-hint] {
      color: var(--dsw-alias-label-tertiary, #8b93a1) !important;
      font-size: 12px !important;
      line-height: 16px !important;
    }
    `

    function start(win, React) {
      const doc = win.document
      if (!doc || !doc.documentElement) return { dispose() {} }

      const F = win.__DSH_BUBBLE_FOLD_MODULES__?.fold
      if (!F) throw new Error('[dsh-bubble-fold] fold module missing from bundle')

      const computedStyleOf = win.getComputedStyle.bind(win)

      // ---------------------------------------------------------------- settings
      let settings = F.normalizeSettings(readStored())
      /** anchor element -> { body, tail, toggle, wrapper, kind, anchor } */
      const clamped = new Map()
      /** anchor element -> measurement signature, so settled rows are not re-measured */
      const measured = new Map()
      /** flow item element -> the seam control injected above the bubble that follows it */
      const stepFolds = new Map()
      /** the same key -> whether the plugin folded that block itself (host cannot) */
      const selfFolds = new Map()
      /**
       * Blocks already folded once for the reader. The host renders its own
       * disclosure open, so "steps start folded" means closing it exactly once per
       * block — after that the reader's own choice wins and nothing re-collapses.
       */
      const autoFolded = new Set()
      /**
       * Counters exposed through `__DSH_BUBBLE_FOLD__.stats()`. They exist because
       * a self-feeding scan loop is invisible from the outside: you can only see it
       * as "the interface is slow".
       */
      const stats = { scans: 0, mutations: 0, selfMutations: 0, measured: 0 }
      /** card element -> the drag handle injected into it */
      const composerHandles = new Map()
      let dragState = null
      let composerHeight = readComposerHeight().value
      let composerManual = readComposerHeight().manual
      let styleTag = null
      let panelOpen = false
      let scheduled = false
      let disposed = false

      function readStored() {
        try {
          const raw = win.localStorage?.getItem(F.STORAGE_KEY)
          return raw ? JSON.parse(raw) : null
        } catch {
          return null
        }
      }

      function persist() {
        try {
          win.localStorage?.setItem(F.STORAGE_KEY, JSON.stringify(settings))
        } catch {
          /* private mode: settings simply do not survive a reload */
        }
      }

      function readComposerHeight() {
        try {
          const raw = win.localStorage?.getItem(COMPOSER_STORAGE_KEY)
          if (raw === null || raw === undefined) return { value: COMPOSER_DEFAULT, manual: false }
          const value = Number.parseFloat(raw)
          if (!Number.isFinite(value)) return { value: COMPOSER_DEFAULT, manual: false }
          return {
            value: Math.max(COMPOSER_MIN, Math.min(COMPOSER_MAX, Math.round(value))),
            manual: true
          }
        } catch {
          return { value: COMPOSER_DEFAULT, manual: false }
        }
      }

      // ------------------------------------------------------------------ styles
      function ensureStyles() {
        // `getElementById` can legitimately come back empty (a page without this
        // node yet, or a document that was swapped). Track the node we created so a
        // failed lookup can never stack a second <style> on every scan.
        if (styleTag !== null && styleTag.isConnected) {
          if (styleTag.textContent !== CSS) styleTag.textContent = CSS
          return
        }
        styleTag = doc.getElementById(F.STYLE_ID)
        if (!styleTag) {
          styleTag = doc.createElement('style')
          styleTag.setAttribute('id', F.STYLE_ID)
          styleTag.setAttribute('data-plugin-css', F.STYLE_ID)
          doc.head.appendChild(styleTag)
        }
        if (styleTag.textContent !== CSS) styleTag.textContent = CSS
      }

      function applyRootFlag() {
        if (settings.enabled) doc.documentElement.setAttribute(F.ROOT_ATTRIBUTE, 'on')
        else doc.documentElement.removeAttribute(F.ROOT_ATTRIBUTE)
      }

      // ---------------------------------------------------------------- geometry
      function lineHeightOf(element) {
        const computed = computedStyleOf(element)
        const base = Number.parseFloat(computed.lineHeight)
        const delta = Number.parseFloat(computed.getPropertyValue('--dsh-content-font-delta')) || 0
        if (Number.isFinite(base) && base > 0) return base + delta
        const font = Number.parseFloat(computed.fontSize)
        return Number.isFinite(font) && font > 0 ? font * 1.5 : 22
      }

      function fadeColorOf(element) {
        let node = element
        for (let depth = 0; depth < 6 && node; depth += 1) {
          const background = computedStyleOf(node).backgroundColor
          if (background && background !== 'transparent' && !/rgba?\([^)]*,\s*0\s*\)/.test(background)) return background
          node = node.parentElement
        }
        return 'var(--dsw-alias-bg-base, #ffffff)'
      }

      function isStreaming(anchor) {
        return Boolean(anchor.querySelector('[data-streaming]'))
      }

      function skipReason(anchor) {
        return anchor.closest(SKIP_ANCESTORS)
      }

      function messageBodyOf(anchor, kind) {
        if (kind === KIND_USER || kind === KIND_STEERING) {
          const stack = anchor.firstElementChild?.firstElementChild
          if (!stack) return null
          const candidates = stack.children
          // The bubble is the FIRST non-attachment child (attachments render before
          // it, a reference summary after it). Picking the first means the actual
          // text bubble is clamped, never the reference line that follows it.
          for (let i = 0; i < candidates.length; i += 1) {
            const node = candidates[i]
            if (!(node instanceof win.HTMLElement)) continue
            if (node.hasAttribute('data-message-attachments')) continue
            return node
          }
          return null
        }
        if (kind === KIND_ASSISTANT) {
          const root = anchor.querySelector('[data-streaming]') ?? anchor.querySelector('div')
          if (!root) return null
          const body = root.firstElementChild
          return body instanceof win.HTMLElement ? body : null
        }
        return null
      }

      // -------------------------------------------------------- work-step folding
      /**
       * ONE control per PROCESS BLOCK: the run of work-step rows that sits between
       * two message bubbles. The seam lives immediately ABOVE the bubble that
       * follows the block, so one click folds everything between the two bubbles.
       *
       * Two host layouts exist and both are handled here:
       *
       *   1. GROUPED (work-details compact / standard, and history for closed
       *      turns). The steps are nested inside a `[data-step-process]` container
       *      whose own header button is the disclosure, and each Turn may also
       *      render its `[data-turn-process]` summary row. The seam clicks those
       *      host controls — the host stays the single owner of the state.
       *   2. FLAT / INLINE (work-details verbose). No disclosure is offered: the
       *      host renders a disabled summary row and every step inline. There the
       *      seam folds the rows itself, display-only, exactly like a long message
       *      bubble: an attribute on the rows, removed the moment the plugin is
       *      disabled.
       */
      /** A step container, or any flow row (whose kind decides whether it is a step). */
      const STEP_UNIT = '[data-step-process],[data-chat-flow-kind]'
      /** Ancestors that mean "this is not part of the conversation's step flow". */
      const BLOCK_SKIP = [
        '[data-context-fields]',
        '[data-context-text]',
        '[data-context-injection-body]',
        '[data-system-prompt-body]',
        '[data-message-attachments]'
      ].join(',')

      /** True for a Turn summary row, a grouped step container, or a flat member row. */
      function isProcessUnit(element) {
        return element.hasAttribute('data-step-process')
          || element.hasAttribute('data-turn-process-member')
          || element.getAttribute('data-chat-flow-kind') === KIND_TURN_PROCESS
      }

      const isOurControl = (element) => element.hasAttribute('data-lf-step-toggle')

      /** The next unit inside the same block; our own seam is skipped, not a wall. */
      function blockUnitAfter(element) {
        let node = element.nextElementSibling
        while (node && isOurControl(node)) node = node.nextElementSibling
        return node && isProcessUnit(node) ? node : null
      }

      function blockUnitBefore(element) {
        let node = element.previousElementSibling
        while (node && isOurControl(node)) node = node.previousElementSibling
        return node && isProcessUnit(node) ? node : null
      }

      /** First sibling after the block that is not part of it — the following bubble. */
      function blockTailAfter(element) {
        let node = element.nextElementSibling
        while (node && isOurControl(node)) node = node.nextElementSibling
        return node
      }

      /**
       * The host disclosure for one unit, when the host actually offers one.
       * `null` means the host renders this unit inline and cannot fold it.
       */
      function hostControlOf(unit) {
        // A Turn's own summary row ("已完成，用时 …").
        if (unit.getAttribute('data-chat-flow-kind') === KIND_TURN_PROCESS) {
          const control = unit.querySelector('[data-turn-process]')
          if (!control || control !== unit.querySelector('[data-turn-process]')) return null
          // `aria-expanded` absent = the host renders the row without a disclosure;
          // `disabled` = it is foldable in principle but nothing to fold right now.
          if (control.disabled === true || control.getAttribute('aria-expanded') === null) return null
          return { control, kind: 'turn' }
        }
        // A grouped step container: its own header button is the disclosure. A
        // container rendered in expanded mode has a hidden header and no fold.
        if (unit.hasAttribute('data-step-process')) {
          if (unit.hasAttribute('data-group-expanded-mode')) return null
          const icon = unit.querySelector('[data-step-process-icon]')
          const button = icon?.closest('button') ?? unit.querySelector('button[aria-controls]')
          if (!button || button.getAttribute('aria-expanded') === null) return null
          return { control: button, kind: 'group' }
        }
        return null
      }

      const controlIsOpen = (descriptor) => (descriptor.kind === 'group'
        ? descriptor.control.getAttribute('aria-expanded') === 'true'
        : descriptor.control.hasAttribute('data-open'))

      /** Split a block into host-driven controls and rows the plugin may hide itself. */
      function decomposeBlock(items) {
        const controls = []
        const own = []
        for (const item of items) {
          const descriptor = hostControlOf(item)
          if (descriptor) controls.push(descriptor)
          else own.push(item)
        }
        return { controls, own }
      }

      /** The block around one of our seams, re-read from the live DOM at click time. */
      function blockAround(seam) {
        const items = []
        for (let node = blockUnitBefore(seam); node; node = blockUnitBefore(node)) items.unshift(node)
        for (let node = blockUnitAfter(seam); node; node = blockUnitAfter(node)) items.push(node)
        return items
      }

      /** Display-only fold marks for blocks the host itself refuses to fold. */
      function applyFoldMarks(items, folded) {
        for (const item of items) {
          if (folded) setAttr(item, FOLD_MARK, '1')
          else removeAttr(item, FOLD_MARK)
        }
      }

      /**
       * Whether a block is folded right now. A block the host can fold follows the
       * host's own disclosure; one the host renders inline follows our own flag,
       * which starts folded (nothing hides until the reader asks it to).
       */
      function isBlockFolded(tail, controls) {
        if (controls.length > 0) return !controls.some(controlIsOpen)
        if (settings.foldAllSteps) return selfFolds.get(tail) !== false
        return selfFolds.get(tail) === true
      }

      /** How many step rows a block actually holds, nested ones included. */
      function stepCountOf(items) {
        let count = 0
        for (const item of items) {
          if (item.hasAttribute('data-turn-process-member')) count += 1
          else count += item.querySelectorAll('[data-turn-process-member]').length
        }
        return count
      }

      function syncStepFolds() {
        if (!settings.enabled || !settings.workStepButtons) {
          for (const [tail, fold] of stepFolds) {
            fold.remove()
            stepFolds.delete(tail)
          }
          for (const row of doc.querySelectorAll(`[${FOLD_MARK}]`)) row.removeAttribute(FOLD_MARK)
          selfFolds.clear()
          autoFolded.clear()
          return
        }
        const seen = new Set()
        const live = new Set()
        for (const unit of doc.querySelectorAll(STEP_UNIT)) {
          if (seen.has(unit) || !isProcessUnit(unit)) continue
          // Only top-level units: rows nested inside a step container belong to it.
          const owner = unit.closest('[data-step-process]')
          if (owner && owner !== unit) continue
          const parent = unit.parentElement
          if (!parent || parent.closest(BLOCK_SKIP)) continue

          // Walk back to the block's first row, then collect the run forward. The
          // `seen` set keeps this linear: only a block's first row walks backwards.
          let first = unit
          for (let previous = blockUnitBefore(first); previous; previous = blockUnitBefore(first)) first = previous
          const items = []
          for (let node = first; node; node = blockUnitAfter(node)) {
            items.push(node)
            seen.add(node)
          }

          const last = items[items.length - 1]
          const tail = blockTailAfter(last)
          // No bubble below yet (a Turn still running): the seam belongs between the
          // steps and that bubble, so there is nothing to attach it to. It appears
          // the moment the reply lands.
          if (!tail || !tail.isConnected) continue

          const { controls, own } = decomposeBlock(items)
          if (controls.length === 0 && own.length === 0) continue
          const selfFold = controls.length === 0
          // Seams are created lazily, like every other injected node: a long
          // conversation holds hundreds of blocks and each insertion re-triggers the
          // observer that scheduled this pass.
          if (!isNearViewport(tail) && !stepFolds.has(tail)) continue

          live.add(tail)
          let fold = stepFolds.get(tail)
          if (fold && (!fold.isConnected || fold.parentElement !== parent)) {
            fold.remove()
            stepFolds.delete(tail)
            fold = undefined
          }
          if (!fold) {
            fold = stepBubble()
            stepFolds.set(tail, fold)
          }
          // Idempotent placement: the seam always sits immediately above the bubble,
          // so a host re-render that moved it is corrected without a second write.
          if (fold.parentElement !== parent || fold.nextElementSibling !== tail) {
            parent.insertBefore(fold, tail)
          }

          // Steps start folded — the newest Turn's included. Who does the folding
          // depends on the layout: the host's own disclosure when there is one, our
          // own display-only mark when the host offers none.
          if (settings.foldAllSteps && !autoFolded.has(tail)) {
            autoFolded.add(tail)
            if (selfFold) selfFolds.set(tail, true)
            else for (const descriptor of controls) if (controlIsOpen(descriptor)) descriptor.control.click()
          }

          const folded = isBlockFolded(tail, controls)
          const open = !folded
          // The host owns its own rows; only a block the host refuses to fold gets
          // our mark, and the write is idempotent so it cannot feed the scan loop.
          if (selfFold) applyFoldMarks(items, folded)

          const label = open ? '收起步骤' : '展开步骤'
          const hidden = folded ? stepCountOf(items) : 0
          const title = hidden > 0 ? `${label} · ${hidden} 步` : label
          if (fold.getAttribute('aria-label') !== label) fold.setAttribute('aria-label', label)
          if (fold.getAttribute('title') !== title) fold.setAttribute('title', title)
          if (fold.getAttribute('aria-expanded') !== String(open)) {
            fold.setAttribute('aria-expanded', String(open))
          }
          setAttr(fold, 'data-lf-step-open', open ? '1' : '0')
          if (fold.hidden) fold.hidden = false
        }
        for (const [tail, fold] of [...stepFolds]) {
          if (live.has(tail) && tail.isConnected) continue
          fold.remove()
          stepFolds.delete(tail)
        }
        for (const [tail] of [...selfFolds]) {
          if (tail.isConnected) continue
          selfFolds.delete(tail)
        }
        for (const tail of [...autoFolded]) {
          if (tail.isConnected) continue
          autoFolded.delete(tail)
        }
      }

      // ------------------------------------------------------------------ clamping
      /** A downward chevron for both control styles; CSS flips it when open. */
      const CHEVRON_ICON = '<svg viewBox="0 0 16 16" fill="none" aria-hidden="true"><path d="M4 6l4 4 4-4" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>'

      /** A bubble-styled capsule button: chevron icon + label text. */
      function controlButton(label, attribute, value = '1') {
        const button = doc.createElement('button')
        button.type = 'button'
        button.setAttribute(attribute, value)
        const icon = doc.createElement('span')
        icon.setAttribute('aria-hidden', 'true')
        icon.innerHTML = CHEVRON_ICON
        const text = doc.createElement('span')
        text.setAttribute('data-lf-label', '1')
        text.textContent = label
        button.append(icon, text)
        return button
      }

      /** The seam control for one process block: a bubble on a hairline divider. */
      function stepBubble() {
        const button = doc.createElement('button')
        button.type = 'button'
        button.setAttribute('data-lf-step-toggle', '1')
        const bubble = doc.createElement('span')
        bubble.setAttribute('data-lf-bubble', '1')
        bubble.setAttribute('aria-hidden', 'true')
        bubble.innerHTML = CHEVRON_ICON
        button.appendChild(bubble)
        return button
      }

      /** Set ONLY the label span, leaving the chevron icon in place. */
      function setLabel(button, label) {
        const text = button.querySelector('[data-lf-label]')
        if (text && text.textContent !== label) text.textContent = label
      }

      function wrap(anchor, kind, body) {
        const wrapper = doc.createElement('div')
        wrapper.setAttribute('data-lf-body', kind)
        body.parentNode?.insertBefore(wrapper, body)
        wrapper.appendChild(body)
        // Deliberately NOT setting data-lf-clamped here: measureAndClamp decides,
        // and it writes only on change.

        const tail = doc.createElement('div')
        tail.setAttribute('data-lf-tail', kind)
        tail.hidden = true
        // Exactly ONE control per message: its own 展开 / 收起. Bulk actions were
        // removed — they were confusing, they had nothing to act on beyond these
        // same toggles, and their hover styling fought the per-scan writes.
        const toggle = controlButton('', 'data-lf-toggle')
        toggle.setAttribute('aria-expanded', 'false')
        tail.appendChild(toggle)
        anchor.appendChild(tail)

        const record = { body, tail, toggle, wrapper, kind, anchor }
        clamped.set(anchor, record)
        return record
      }

      function unwrap(anchor) {
        const record = clamped.get(anchor)
        if (!record) return
        clipped(record)
        record.tail.remove()
        const body = record.body
        body.removeAttribute('data-lf-clamped')
        body.removeAttribute('data-lf-open')
        record.wrapper.style.removeProperty('--lf-clamp-height')
        record.wrapper.style.removeProperty('--lf-allowance')
        record.wrapper.style.removeProperty('--lf-fade-color')
        if (record.wrapper.parentNode) {
          record.wrapper.parentNode.insertBefore(body, record.wrapper)
          record.wrapper.remove()
        }
        clamped.delete(anchor)
        measured.delete(anchor)
      }

      function clipAll() {
        for (const anchor of [...clamped.keys()]) unwrap(anchor)
        // Safety net: the clamp value lives in the wrapper's inline variables, so an
        // orphaned attribute (a body React moved out from under it) must not be left
        // able to bound anything.
        for (const stale of doc.querySelectorAll('[data-lf-clamped]')) stale.removeAttribute('data-lf-clamped')
        for (const row of doc.querySelectorAll('[data-lf-tail]')) row.remove()
        for (const fold of doc.querySelectorAll('[data-lf-step-toggle]')) fold.remove()
        for (const row of doc.querySelectorAll(`[${FOLD_MARK}]`)) row.removeAttribute(FOLD_MARK)
        stepFolds.clear()
        selfFolds.clear()
      }

      function isOpen(body) {
        return body.getAttribute('data-lf-open') === '1'
      }

      /**
       * Set an attribute ONLY when the value actually changes.
       *
       * This is load-bearing, not a micro-optimisation: the plugin's own
       * MutationObserver watches these attributes, so an unconditional
       * `setAttribute` with an unchanged value still queues a mutation record and
       * schedules another scan — which writes again. That self-feeding loop runs at
       * requestAnimationFrame rate forever and is what makes a long conversation
       * (1000+ flow items) unusable.
       */
      function setAttr(element, name, value) {
        if (element.getAttribute(name) === value) return false
        element.setAttribute(name, value)
        return true
      }

      function removeAttr(element, name) {
        if (!element.hasAttribute(name)) return false
        element.removeAttribute(name)
        return true
      }

      function setOpen(anchor, record, open) {
        const { body, toggle } = record
        setAttr(body, 'data-lf-open', open ? '1' : '0')
        setAttr(toggle, 'aria-expanded', open ? 'true' : 'false')
        setLabel(toggle, open ? '收起' : labelFor(record))
      }

      function labelFor(record) {
        const { body, kind } = record
        const lines = F.hiddenLineLabel(body.scrollHeight, body.getBoundingClientRect().height, lineHeightOf(body))
        const name = kind === F.SIDE_USER ? '展开我的输入' : '展开全文'
        return lines ? `${name} · ${lines}` : name
      }

      function refreshLabel(record) {
        if (!isOpen(record.body)) setLabel(record.toggle, labelFor(record))
      }

      function measureAndClamp(anchor, side, record) {
        const { body } = record
        const lineHeight = lineHeightOf(body)
        const limits = F.settingsForSide(settings, side)
        const lines = settings.collapseAll ? settings.collapsedLines : limits.lines
        // The visible budget is the natural line position; the CSS adds its own
        // allowance band below it for the fade, so the mask never covers a line the
        // reader is supposed to see.
        const contentBudget = F.clampHeightFor(lines, lineHeight, 0)
        const allowance = F.allowanceFor(settings.extraPx)

        // Measurement must happen while the body is NOT clamped, otherwise
        // scrollHeight reflects the constrained box instead of the real content.
        removeAttr(body, 'data-lf-clamped')
        const natural = body.scrollHeight
        const overflows = natural > contentBudget + 8

        if (overflows) {
          setAttr(body, 'data-lf-clamped', '1')
          // Keep the collapsed/expanded flag explicit for every folded body, so a
          // missing attribute never has to be read as "collapsed by accident".
          if (!body.hasAttribute('data-lf-open')) setAttr(body, 'data-lf-open', '0')
          record.wrapper.style.setProperty('--lf-clamp-height', `${contentBudget}px`)
          record.wrapper.style.setProperty('--lf-allowance', `${allowance}px`)
          record.wrapper.style.setProperty('--lf-fade-color', fadeColorOf(body))
          if (!isOpen(body)) setLabel(record.toggle, labelFor(record))
        } else {
          removeAttr(body, 'data-lf-clamped')
          removeAttr(body, 'data-lf-open')
        }

        if (!overflows) setAttr(record.tail, 'hidden', '')
        else removeAttr(record.tail, 'hidden')
        return overflows
      }

      function clipped(record) {
        setAttr(record.tail, 'hidden', '')
        setAttr(record.body, 'data-lf-open', '0')
      }

      // ------------------------------------------------------------ visibility
      /**
       * The conversation holds over a thousand flow items. Anything that measures or
       * writes across all of them costs a synchronous layout per item, so both the
       * clamp pass and the work-step rows are limited to what is actually on screen
       * (plus a screen of margin, so scrolling never reveals an unfitted message).
       */
      function isNearViewport(element) {
        const rect = element.getBoundingClientRect()
        const height = win.innerHeight || 800
        return rect.bottom > -height && rect.top < height * 2
      }

      // ---------------------------------------------------------------- turn ids
      /** The Turn one flow row belongs to, as the host numbers it, or null. */
      function turnIdOf(element) {
        const raw = element.getAttribute('data-chat-turn')
        if (raw === null || raw === '') return null
        const value = Number(raw)
        return Number.isFinite(value) ? value : null
      }

      /**
       * The newest Turn in the conversation. Read from the rows themselves rather
       * than from scroll position: a Turn is "latest" while its reply is the last
       * thing that happened, no matter where the reader has scrolled to.
       */
      function latestTurnId() {
        let latest = null
        for (const element of doc.querySelectorAll('[data-chat-turn]')) {
          const value = turnIdOf(element)
          if (value === null) continue
          if (latest === null || value > latest) latest = value
        }
        return latest
      }

      // -------------------------------------------------------------------- scan
      function scan() {
        if (disposed) return
        ensureStyles()
        applyRootFlag()
        stats.scans += 1

        if (!settings.enabled) {
          if (clamped.size > 0) clipAll()
          return
        }

        const seen = new Set()
        const streaming = []
        const startedAt = now()
        let budgetLeft = true
        // The newest Turn is what the reader came for: its messages stay open even
        // when they are long. Older Turns fold down to their line budget.
        const latestTurn = settings.keepLatestOpen ? latestTurnId() : null

        for (const anchor of doc.querySelectorAll(FLOW_ITEM)) {
          // Yield between rows: a frame that touches a thousand flow items is what
          // made the interface stutter. Rows skipped here are picked up by the next
          // scheduled pass, and scrolling schedules one.
          if (budgetLeft && now() - startedAt > SCAN_BUDGET_MS) {
            budgetLeft = false
            schedule()
          }
          const flowKind = anchor.getAttribute('data-chat-flow-kind')
          if (flowKind !== KIND_USER && flowKind !== KIND_STEERING && flowKind !== KIND_ASSISTANT) continue
          // The DOM kind ("assistant-step") and the side ("assistant") are distinct;
          // settings and the anchor marker both use the side.
          const side = flowKind === KIND_ASSISTANT ? F.SIDE_ASSISTANT : F.SIDE_USER
          const limits = F.settingsForSide(settings, side)
          const existing = clamped.get(anchor)

          // The latest Turn never folds — not even by collapseAll.
          if (latestTurn !== null && turnIdOf(anchor) === latestTurn) {
            unwrap(anchor)
            continue
          }

          // Cheap, non-measuring branch: keep the bookkeeping honest for every row.
          if (!limits.enabled || skipReason(anchor) || (side === F.SIDE_ASSISTANT && isStreaming(anchor))) {
            if (side === F.SIDE_ASSISTANT && isStreaming(anchor)) streaming.push(anchor)
            unwrap(anchor)
            continue
          }
          // Off-screen rows keep whatever fit they already have: measuring each one
          // costs a forced layout, and nobody can see the result.
          if (existing === undefined && !isNearViewport(anchor)) continue

          seen.add(anchor)
          stats.measured += 1
          const lines = settings.collapseAll ? settings.collapsedLines : limits.lines

          let record = existing
          if (record && (!record.body.isConnected || !record.wrapper.isConnected || record.body.parentNode !== record.wrapper)) {
            // React replaced the subtree underneath us; drop the stale record and re-clamp.
            clamped.delete(anchor)
            measured.delete(anchor)
            record = undefined
          }
          if (!record) {
            const body = messageBodyOf(anchor, flowKind)
            if (!body) continue
            record = wrap(anchor, side, body)
          }
          // Skip the measurement pass for settled rows whose geometry has not moved.
          const signature = `${record.body.scrollHeight}|${lines}|${settings.extraPx}|${record.tail.hidden ? 0 : 1}`
          if (measured.get(anchor) === signature) continue
          measured.set(anchor, signature)
          measureAndClamp(anchor, side, record)
        }

        if (budgetLeft) {
          for (const anchor of [...clamped.keys()]) {
            if (!seen.has(anchor) && !streaming.includes(anchor)) unwrap(anchor)
          }
          syncStepFolds()
          syncComposerGrip()
        }
      }

      function now() {
        return win.performance?.now ? win.performance.now() : Date.now()
      }

      function schedule() {
        if (scheduled || disposed) return
        scheduled = true
        const run = () => {
          scheduled = false
          scan()
        }
        if (typeof win.requestAnimationFrame === 'function') win.requestAnimationFrame(run)
        else win.setTimeout(run, 60)
      }

      // ---------------------------------------------------------------- settings
      // There is deliberately NO standing overlay: a floating bar overlaps the
      // composer. Bulk actions live in each message's control row, and settings open
      // as a dismissible dialog.
      let panel = null
      let scrim = null

      function buildPanel() {
        panel = doc.createElement('div')
        panel.setAttribute('data-lf-panel', '1')

        const title = doc.createElement('h4')
        // 用户消息是气泡，助手回复是正文块，统称"消息"才不会误导。
        title.textContent = '消息与步骤折叠'
        panel.appendChild(title)

        const row = (labelText, control) => {
          const label = doc.createElement('label')
          const span = doc.createElement('span')
          span.textContent = labelText
          label.append(span, control)
          panel.appendChild(label)
          return control
        }

        const number = (key, min, max) => {
          const input = doc.createElement('input')
          input.type = 'number'
          input.min = String(min)
          input.max = String(max)
          input.value = String(settings[key])
          input.setAttribute('data-lf-key', key)
          input.addEventListener('change', () => {
            settings = F.normalizeSettings({ ...settings, [key]: input.value })
            input.value = String(settings[key])
            persist()
            scan()
          })
          return input
        }

        const checkbox = (key) => {
          const input = doc.createElement('input')
          input.type = 'checkbox'
          input.checked = Boolean(settings[key])
          input.setAttribute('data-lf-key', key)
          input.addEventListener('change', () => {
            settings = F.normalizeSettings({ ...settings, [key]: input.checked })
            persist()
            scan()
            syncPanel()
          })
          return input
        }

        row('启用插件', checkbox('enabled'))
        row('最新一轮保持展开', checkbox('keepLatestOpen'))
        row('折叠我的输入', checkbox('userEnabled'))
        row('我的输入保留行数', number('userLines', F.LIMITS.minLines, F.LIMITS.maxLines))
        row('折叠助手回复', checkbox('assistantEnabled'))
        row('助手回复保留行数', number('assistantLines', F.LIMITS.minLines, F.LIMITS.maxLines))
        row('全部消息都折叠', checkbox('collapseAll'))
        row('折叠后保留行数', number('collapsedLines', F.LIMITS.minLines, F.LIMITS.maxDefaultCollapsedLines))
        row('淡出与按钮留白 (px)', number('extraPx', F.LIMITS.minExtraPx, F.LIMITS.maxExtraPx))
        row('步骤区与回复之间加折叠按钮', checkbox('workStepButtons'))
        row('步骤默认收起', checkbox('foldAllSteps'))
        row('输入框可拖动调高', checkbox('composerResize'))

        // The composer height is not a plugin setting: it drives the host's own CSS
        // variable, so it gets its own control rather than the settings schema.
        const heightInput = doc.createElement('input')
        heightInput.type = 'number'
        heightInput.min = String(COMPOSER_MIN)
        heightInput.max = String(COMPOSER_MAX)
        heightInput.value = String(composerHeight)
        heightInput.setAttribute('data-lf-height', '1')
        heightInput.addEventListener('change', () => {
          const value = Number.parseFloat(heightInput.value)
          if (Number.isFinite(value)) setComposerHeight(value)
          else resetComposerHeight()
        })
        row(`输入框高度 (${COMPOSER_MIN}–${COMPOSER_MAX}px，留空恢复默认)`, heightInput)

        const footer = doc.createElement('footer')
        const hint = doc.createElement('span')
        hint.setAttribute('data-lf-hint', '1')
        hint.textContent = '仅改显示，不动会话'
        const close = doc.createElement('button')
        close.type = 'button'
        close.setAttribute('data-lf-act', 'close-panel')
        close.textContent = '关闭'
        const reset = doc.createElement('button')
        reset.type = 'button'
        reset.setAttribute('data-lf-act', 'reset')
        reset.textContent = '恢复默认'
        footer.append(hint, reset, close)
        panel.appendChild(footer)
        return panel
      }

      function syncPanel() {
        if (!panel) return
        for (const input of panel.querySelectorAll('[data-lf-key]')) {
          const key = input.getAttribute('data-lf-key')
          if (input.type === 'checkbox') input.checked = Boolean(settings[key])
          else input.value = String(settings[key])
          const gate = TIE[key]
          input.disabled = gate ? !settings[gate] : false
          if (gate) input.title = `需要先开启「${TIE_LABEL[gate]}」`
          else input.removeAttribute('title')
        }
        // Never rewrite a field the user is typing in: sync runs on every scan.
        const heightInput = panel.querySelector('[data-lf-height]')
        if (heightInput && doc.activeElement !== heightInput) heightInput.value = String(composerHeight)
      }

      function togglePanel(open) {
        panelOpen = open ?? !panelOpen
        if (panelOpen) {
          if (!panel) {
            panel = buildPanel()
            scrim = doc.createElement('div')
            scrim.setAttribute('data-lf-scrim', '1')
            doc.body.append(scrim, panel)
          }
          syncPanel()
          panel.hidden = false
          if (scrim) scrim.hidden = false
        } else {
          if (panel) panel.hidden = true
          if (scrim) scrim.hidden = true
        }
      }

      function closePanel() {
        togglePanel(false)
      }

      // ------------------------------------------------------- composer resizing
      // The host caps the composer at `--dsh-composer-text-max-height` (336px by
      // default) and scrolls inside that. Manually adjusting the height therefore
      // means raising that cap; the content still grows on its own up to it.
      const COMPOSER_MIN = 72
      const COMPOSER_MAX = 1400

      function composerSeats() {
        return [...doc.querySelectorAll('[data-composer-seat]')]
      }

      /**
       * The seat's first child is NOT the card: the host renders a zero-height
       * placeholder slot first, and a handle placed there is unreachable — pointer
       * hits land on the wrapper instead, so real mouse input never reaches it.
       * The card is the element that actually contains the input, so find it by
       * that relationship rather than by position or by a hashed class name.
       */
      function composerCardOf(seat) {
        for (const child of seat.children) {
          if (child.querySelector('[contenteditable="true"]')) return child
        }
        return seat.lastElementChild ?? seat.firstElementChild
      }

      /**
       * The host caps the input at max-height and scrolls inside; raising the cap
       * alone changes NOTHING visually while the content is short, which is why the
       * first drag seemed dead. When the user takes manual control we also pin the
       * scroll area with a min-height, so the box actually grows to the chosen size
       * (and still auto-scrolls once content passes it).
       */
      function composerScrollOf(card) {
        for (const node of card.querySelectorAll('*')) {
          let style
          try {
            style = win.getComputedStyle(node)
          } catch {
            continue
          }
          if (style?.overflowY === 'auto') return node
        }
        return null
      }

      function applyComposerHeight() {
        for (const seat of composerSeats()) {
          seat.style.setProperty('--dsh-composer-text-max-height', `${composerHeight}px`)
          const card = composerCardOf(seat)
          const scroll = card ? composerScrollOf(card) : null
          if (!scroll) continue
          if (composerManual) scroll.style.setProperty('min-height', `${composerHeight}px`)
          else scroll.style.removeProperty('min-height')
        }
      }

      function setComposerHeight(value) {
        const next = Math.max(COMPOSER_MIN, Math.min(COMPOSER_MAX, Math.round(value)))
        if (next === composerHeight && composerManual) return
        composerHeight = next
        composerManual = true
        try {
          win.localStorage?.setItem(COMPOSER_STORAGE_KEY, String(next))
        } catch {
          /* private mode: the height simply does not survive a reload */
        }
        applyComposerHeight()
        syncPanel()
      }

      function resetComposerHeight() {
        composerHeight = COMPOSER_DEFAULT
        composerManual = false
        try {
          win.localStorage?.removeItem(COMPOSER_STORAGE_KEY)
        } catch {
          /* private mode */
        }
        applyComposerHeight()
        syncPanel()
      }

      /**
       * Add one thin drag handle to every composer card. It lives INSIDE the card's
       * flex column, so it can never overlap the input, the toolbar row, or the
       * send button.
       */
      function syncComposerGrip() {
        if (!settings.composerResize || !settings.enabled) {
          for (const [, handle] of composerHandles) handle.remove()
          composerHandles.clear()
          return
        }
        const wanted = new Set()
        for (const seat of composerSeats()) {
          applyComposerHeight()
          const card = composerCardOf(seat)
          if (!card) continue
          wanted.add(card)
          const live = composerHandles.get(card)
          // Validity is the PARENT relationship, not mere connectivity: on first run
          // the card may not be rendered yet, and a handle parked in the seat's
          // placeholder slot stays "connected" forever while being unreachable —
          // pointer hits land on the wrapper instead of the handle.
          if (live && live.isConnected && live.parentElement === card) continue
          if (live) {
            live.remove()
            composerHandles.delete(card)
          }
          const handle = doc.createElement('div')
          handle.setAttribute('data-lf-composer-handle', '1')
          handle.setAttribute('role', 'separator')
          handle.setAttribute('aria-orientation', 'horizontal')
          handle.setAttribute('aria-label', '拖动调整输入框高度；双击恢复默认')
          card.insertBefore(handle, card.firstChild)
          composerHandles.set(card, handle)
        }
        for (const [card, handle] of [...composerHandles]) {
          if (wanted.has(card) && card.isConnected && handle.parentElement === card) continue
          handle.remove()
          composerHandles.delete(card)
        }
        // Sweep strays from an earlier run that landed somewhere we no longer track.
        for (const stray of doc.querySelectorAll('[data-lf-composer-handle]')) {
          if (stray.parentElement && stray.parentElement.querySelector('[contenteditable="true"]')) continue
          stray.remove()
        }
      }

      /**
       * The pixel height the input scroll area actually occupies right now. The
       * first drag must start from THIS, not from the cap: otherwise the first
       * pointermove snaps the box from its natural size to the full cap in one
       * jump instead of growing continuously with the pointer.
       */
      function composerVisualHeight(seat) {
        const card = composerCardOf(seat)
        const scroll = card ? composerScrollOf(card) : null
        const rect = scroll?.getBoundingClientRect?.()
        return rect && rect.height > 0 ? Math.round(rect.height) : composerHeight
      }

      function firstSeatVisualHeight() {
        const seat = composerSeats()[0]
        return seat ? composerVisualHeight(seat) : composerHeight
      }

      function onPointerDown(event) {
        const target = event.target
        if (!(target instanceof win.Element)) return
        const handle = target.closest('[data-lf-composer-handle]')
        if (!handle) return
        event.preventDefault()
        dragState = {
          handle,
          startY: event.clientY ?? 0,
          startVisual: firstSeatVisualHeight()
        }
        setAttr(handle, 'data-dragging', '1')
        win.addEventListener('pointermove', onPointerMove)
        win.addEventListener('pointerup', onPointerUp)
        win.addEventListener('pointercancel', onPointerUp)
      }

      function onPointerMove(event) {
        if (!dragState) return
        // The handle is the TOP EDGE of the composer: pulling it UP must raise the
        // edge and grow the box, so the pointer keeps touching the handle the whole
        // drag (up = taller, down = shorter).
        const delta = (event.clientY ?? 0) - dragState.startY
        setComposerHeight(dragState.startVisual - delta)
      }

      function onPointerUp() {
        if (!dragState) return
        removeAttr(dragState.handle, 'data-dragging')
        dragState = null
        win.removeEventListener('pointermove', onPointerMove)
        win.removeEventListener('pointerup', onPointerUp)
        win.removeEventListener('pointercancel', onPointerUp)
      }

      function onDoubleClick(event) {
        const target = event.target
        if (!(target instanceof win.Element)) return
        if (!target.closest('[data-lf-composer-handle]')) return
        resetComposerHeight()
      }

      // ------------------------------------------------------------------ events
      function onClick(event) {
        const target = event.target
        if (!(target instanceof win.Element)) return

        // A bubble's own toggle: flips just that message.
        const toggle = target.closest('[data-lf-toggle]')
        if (toggle) {
          for (const [anchor, record] of clamped.entries()) {
            if (record.toggle === toggle) {
              setOpen(anchor, record, !isOpen(record.body))
              break
            }
          }
          return
        }

        // A step block's seam. Folded → unfold: open the host's own disclosure where
        // there is one, or drop our display-only mark where there is not. Unfolded →
        // fold: the reverse. Either way a scan follows immediately so the chevron and
        // label cannot lag behind.
        const stepFold = target.closest('[data-lf-step-toggle]')
        if (stepFold) {
          const items = blockAround(stepFold)
          if (items.length > 0) {
            const { controls } = decomposeBlock(items)
            const tail = blockTailAfter(items[items.length - 1])
            const folded = isBlockFolded(tail, controls)
            if (controls.length > 0) {
              // Both directions go through the host, so its own header never
              // disagrees with what the reader sees.
              for (const descriptor of controls) {
                if (descriptor.control.disabled === true) continue
                if (controlIsOpen(descriptor) === folded) continue
                descriptor.control.click()
              }
            } else if (tail) {
              selfFolds.set(tail, !folded)
            }
            // The reader made a choice: never auto-collapse this block again.
            if (tail) autoFolded.add(tail)
            schedule()
          }
          return
        }

        const action = target.closest('[data-lf-act]')?.getAttribute('data-lf-act')
        if (action === 'close-panel' || target === scrim) closePanel()
        else if (action === 'reset') {
          settings = F.normalizeSettings(null)
          persist()
          measured.clear()
          scan()
          syncPanel()
        }
      }

      function onKeydown(event) {
        if (event.key === 'Escape' && panelOpen) {
          closePanel()
          return
        }
        if (!event.ctrlKey || !event.shiftKey || event.altKey) return
        const active = doc.activeElement
        if (active instanceof win.HTMLElement && (
          active.tagName === 'INPUT' ||
          active.tagName === 'TEXTAREA' ||
          active.isContentEditable
        )) return
        const key = String(event.key || '').toLowerCase()
        if (key === 'b') {
          settings = F.normalizeSettings({ ...settings, enabled: !settings.enabled })
          persist()
          measured.clear()
          scan()
          syncPanel()
          event.preventDefault()
        } else if ((key === ',' || key === '/') && settings.enabled) {
          // The only way into settings: no floating button, no persistent pill.
          togglePanel()
          event.preventDefault()
        } else if (key === 'arrowup' && settings.enabled) {
          setComposerHeight(composerHeight + F.HEIGHT_STEP)
          event.preventDefault()
        } else if (key === 'arrowdown' && settings.enabled) {
          setComposerHeight(composerHeight - F.HEIGHT_STEP)
          event.preventDefault()
        }
      }

      // Mutations coming from our OWN injected nodes (the control rows and the
      // clamp state) must not schedule another pass. Attribute writes are already
      // idempotent, but React re-rendering the surrounding row can still surface
      // them, and each one used to feed the loop.
      const observer = new win.MutationObserver((records) => {
        stats.mutations += records.length
        let foreign = false
        for (const record of records) {
          const target = record.target
          if (target instanceof win.Element && target.closest('[data-lf-body],[data-lf-tail],[data-lf-step-toggle],[data-lf-panel],[data-lf-scrim]')) {
            stats.selfMutations += 1
            continue
          }
          foreign = true
        }
        if (foreign) schedule()
      })
      ensureStyles()
      applyRootFlag()
      scan()

      // Observe the whole scroll root from the start: at activation time the chat
      // column may not be mounted yet, and the conversation renders inside it later.
      const scope = doc.querySelector('[data-conversation-scroll]') ?? doc.body
      observer.observe(scope, {
        subtree: true,
        childList: true,
        attributes: true,
        attributeFilter: [
          'data-streaming',
          'data-chat-flow-kind',
          'hidden',
          'data-turn-process-hidden',
          'data-turn-process-answer'
        ]
      })
      win.addEventListener('resize', schedule, { passive: true })
      win.addEventListener('scroll', schedule, { passive: true, capture: true })
      doc.addEventListener('click', onClick, true)
      doc.addEventListener('keydown', onKeydown, true)
      doc.addEventListener('pointerdown', onPointerDown, true)
      doc.addEventListener('dblclick', onDoubleClick, true)

      return {
        rescan: schedule,
        settings: () => ({ ...settings }),
        /**
         * Live counters. `scans` climbing while nothing happens means the plugin is
         * feeding itself; `measured` shows how much of each pass touched layout.
         */
        stats: () => ({ ...stats, clamped: clamped.size, stepFolds: stepFolds.size, selfFolds: selfFolds.size }),
        update(patch) {
          settings = F.normalizeSettings({ ...settings, ...patch })
          persist()
          measured.clear()
          scan()
          syncPanel()
        },
        // Manual controls, also available from the console for scripting/tests.
        setHeight: (value) => setComposerHeight(value),
        resetHeight: () => resetComposerHeight(),
        dispose() {
          disposed = true
          observer.disconnect()
          win.removeEventListener('resize', schedule)
          win.removeEventListener('scroll', schedule, { capture: true })
          doc.removeEventListener('click', onClick, true)
          doc.removeEventListener('keydown', onKeydown, true)
          doc.removeEventListener('pointerdown', onPointerDown, true)
          doc.removeEventListener('dblclick', onDoubleClick, true)
          win.removeEventListener('pointermove', onPointerMove)
          win.removeEventListener('pointerup', onPointerUp)
          win.removeEventListener('pointercancel', onPointerUp)
          for (const [, handle] of composerHandles) handle.remove()
          composerHandles.clear()
          for (const seat of composerSeats()) seat.style.removeProperty('--dsh-composer-text-max-height')
          clipAll()
          panel?.remove()
          scrim?.remove()
          panel = null
          scrim = null
          styleTag?.remove()
          styleTag = null
          doc.documentElement.removeAttribute(F.ROOT_ATTRIBUTE)
          if (win.__DSH_BUBBLE_FOLD__) delete win.__DSH_BUBBLE_FOLD__
        }
      }
    }

    return { SCAN_BUDGET_MS, COMPOSER_STORAGE_KEY, COMPOSER_DEFAULT, start }
  })()

  MODULES['./src/fold.js'] = fold
  MODULES['./src/browser.js'] = browser

  // Convenience handle for verifying or driving the plugin from the console:
  //   __DSH_BUBBLE_FOLD__.settings() / .update({...}) / .rescan()
  window.__DSH_BUBBLE_FOLD_MODULES__ = { ...(window.__DSH_BUBBLE_FOLD_MODULES__ ?? {}), ...MODULES }

  // DSH client-plugin entry. Built into ../client.js by scripts/build.mjs.
  //
  // The host calls `registration.factory(require)` with ITS OWN resolver, so:
  //
  //   1. Keep the `require` parameter and use it for platform modules (`react`).
  //      Do not fall back to `window.__ModuleLoader__.require` — it does not exist
  //      during activation, and the plugin then dies with
  //      "[dsh-bubble-fold] host module unavailable: react".
  //   2. Never hand this bundle's own specifiers to that resolver: the host module
  //      table has never heard of "./src/browser.js", and asking it fails with
  //      `client-modules: require("./src/browser.js") missed the module table`,
  //      which the desktop app reports as a failed application boot.
  //
  // So: local modules come from the wrapper's MODULES registry (also exposed on
  // window.__DSH_BUBBLE_FOLD_MODULES__ for console use); everything else goes to
  // the resolver the host passes in.
  //
  // `dsh.client.immediately: true` in package.json is what puts this row in the
  // boot graph — a DOM-only plugin registers no slot, so nothing would ever
  // request it and the bundle would never execute without it.
  window.__ModuleLoader__.load({
    id: 'dsh-bubble-fold',
    factory: (require) => {
      const React = require('react')
      const local = window.__DSH_BUBBLE_FOLD_MODULES__ ?? {}
      const { start } = local['./src/browser.js']
      const fold = local['./src/fold.js']

      // Derive every browser global from the document's own view. Reading bare
      // `getComputedStyle` / `localStorage` globals only works inside a test
      // harness: in the page `getComputedStyle` is brand-checked, so an unbound
      // reference throws "Illegal invocation" the first time layout is measured.
      const view = document.defaultView ?? window

      let controller = null

      const dispose = () => {
        controller?.dispose()
        controller = null
        // Leave no trace of the console handle once the row is gone.
        delete window.__DSH_BUBBLE_FOLD__
      }

      return {
        name: 'dsh-bubble-fold',
        inject: [],
        apply() {
          if (controller !== null) return
          try {
            controller = start({
              document,
              localStorage: view.localStorage,
              getComputedStyle: view.getComputedStyle.bind(view),
              requestAnimationFrame: view.requestAnimationFrame.bind(view),
              setTimeout: view.setTimeout.bind(view),
              clearTimeout: view.clearTimeout.bind(view),
              MutationObserver: view.MutationObserver,
              HTMLElement: view.HTMLElement,
              Element: view.Element,
              addEventListener: view.addEventListener.bind(view),
              removeEventListener: view.removeEventListener.bind(view),
              __DSH_BUBBLE_FOLD_MODULES__: { fold }
            }, React)
          } catch (error) {
            // A failed fold must never take the conversation down with it.
            console.warn('[dsh-bubble-fold] 启动失败，气泡折叠已停用：', error)
            controller = null
          }

          // Console handle: __DSH_BUBBLE_FOLD__.status / .settings() / .stats()
          window.__DSH_BUBBLE_FOLD__ = {
            plugin: 'dsh-bubble-fold',
            status: controller ? 'running' : 'failed',
            rescan: () => controller?.rescan(),
            settings: () => controller?.settings(),
            stats: () => controller?.stats(),
            update: (patch) => controller?.update(patch),
            setHeight: (value) => controller?.setHeight(value),
            resetHeight: () => controller?.resetHeight(),
            dispose
          }

          return dispose
        },
        dispose
      }
    }
  })

})()
