// Bundle src/client-entry.js plus its local modules into ../client.js.
//
// The host's client-plugin loader serves exactly one self-contained file, so the
// local modules are concatenated into a single factory scope. `export` keywords
// are stripped (top-level declarations stay in scope for the entry code), and a
// small registry keeps `require('./src/…')` working — plus exposes the pure fold
// module on window for console-level testing.
import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(here, '..')
const check = process.argv.includes('--check')

const LOCAL_MODULES = [
  ['./src/fold.js', 'fold'],
  ['./src/browser.js', 'browser']
]

const stripExports = (source) => source
  .replace(/^export\s+(?=(?:const|let|var|function|async|class)\b)/gm, '')
  .replace(/^export\s*\{[^}]*\}\s*;?\s*$/gm, '')
  .replace(/^export\s+default\s+/gm, 'const __default__ = ')

/** Public names a module declares, read from its own `export` statements. */
const exportedNamesOf = (source) => {
  const names = []
  for (const match of source.matchAll(/^export\s+(?:const|let|var|function|async function|class)\s+([A-Za-z_$][\w$]*)/gm)) {
    names.push(match[1])
  }
  for (const match of source.matchAll(/^export\s*\{([^}]*)\}/gm)) {
    for (const piece of match[1].split(',')) {
      const name = piece.trim().split(/\s+as\s+/).pop()?.trim()
      if (name) names.push(name)
    }
  }
  return [...new Set(names)]
}

const readLocal = async (relative) => stripExports(await readFile(path.join(root, relative), 'utf8'))

const nameOf = (relative) => LOCAL_MODULES.find(([spec]) => spec === relative)?.[1] ?? relative

const sources = []
for (const [specifier, name] of LOCAL_MODULES) {
  const raw = await readFile(path.join(root, specifier), 'utf8')
  const publicNames = exportedNamesOf(raw)
  if (publicNames.length === 0) throw new Error(`${specifier} declares no exports`)
  sources.push(`  // ---- ${specifier}`)
  sources.push(`  const ${name} = (() => {\n${indent(stripExports(raw), 4)}\n    return { ${publicNames.join(', ')} }\n  })()`)
  sources.push('')
}

const entry = stripExports(await readFile(path.join(root, 'src/client-entry.js'), 'utf8'))

const header = `// Generated by scripts/build.mjs — edit src/*.js and rebuild.
// dsh-bubble-fold — display-only folding for overlong DSH message bubbles.
// Nothing here writes to the session log, the model, or the agent.
`

const bundle = `${header}(function () {
  // Local module registry for this bundle's own sources. The host knows nothing
  // about these specifiers, so the entry must resolve them HERE and hand only
  // real platform modules (react) to the resolver the host passes into factory().
  const MODULES = {}

${sources.join('\n')}
  MODULES['./src/fold.js'] = fold
  MODULES['./src/browser.js'] = browser

  // Convenience handle for verifying or driving the plugin from the console:
  //   __DSH_BUBBLE_FOLD__.settings() / .update({...}) / .rescan()
  window.__DSH_BUBBLE_FOLD_MODULES__ = { ...(window.__DSH_BUBBLE_FOLD_MODULES__ ?? {}), ...MODULES }

${indent(entry, 2)}
})()
`

const target = path.join(root, 'client.js')
if (check) {
  const current = await readFile(target, 'utf8').catch(() => null)
  if (current !== bundle) {
    console.error('client.js is stale — run: node scripts/build.mjs')
    process.exit(1)
  }
  console.log('client.js is up to date')
} else {
  await writeFile(target, bundle, 'utf8')
  console.log(`built ${target} (${bundle.length} chars)`)
}

function indent(source, spaces) {
  const pad = ' '.repeat(spaces)
  return source
    .split('\n')
    .map((line) => (line.trim() === '' ? line : pad + line))
    .join('\n')
}
